- include_tasks: roles/desktop/tasks/main/notify-send-all.yml

- name: Dump all play_stats
  copy:
    content: "{{ ansible_facts | to_json }}"
    dest: /etc/ansible/ansible_facts.json
    mode: '0644'

- name: Print main ansible facts @basic_security_facts
  changed_when: false
  ignore_errors: yes
  command: 'logger "utmost_report: you are here"'