- name: Ensure etckeeper active @ensure_etckeeper_active
  block:
    - name: Ensure etckeeper active Package present @ensure_etckeeper_active
      package:
        name: etckeeper
        state: present
      register: package_result
    - name: Ensure etckeeper active Init @ensure_etckeeper_active
      command:
        cmd: etckeeper init -d /etc
        creates: /etc/.git
  tags:
    - ws
    - ensure_etckeeper_active
