- name: Install gnome-core @install_gnome_core
  block:
    - name: Install gnome-core @install_gnome_core
      package:
        name:
          - gnome-core
        state: present
    - name: Set default to graphical target @install_gnome_core
      command: systemctl set-default graphical.target
  when:
    - var_preffered_desktop is defined
    - var_preffered_desktop == 'gnome'
  tags:
    - ws
    - install_gnome_core