- name: Install required packages @install_nginx_req
  apt:
    name:
      - nginx
      - fcgiwrap
      - spawn-fcgi
      - apache2-utils
    state: present
  tags:
    - dp
    - sec
    - install_nginx_req    

- name: Install nginx certs @create_nginx_certs
  block:
    - name: Install required packages
      apt:
        name:
          - "ssl-cert"
        state: present
      register: result
    - name: Check if snakeoil private key exists
      stat:
        path: /etc/ssl/private/ssl-cert-snakeoil.key
      register: snakeoil_key
    - name: Touch missing private key with secure system permissions
      file:
        path: /etc/ssl/private/ssl-cert-snakeoil.key
        state: touch
        owner: root
        group: ssl-cert
        mode: '0640'
      when: not snakeoil_key.stat.exists
    - name: Generate default snakeoil SSL certificates
      command:
        cmd: make-ssl-cert generate-default-snakeoil --force-overwrite
      when: result.changed or not snakeoil_key.stat.exists
  tags:
    - dp
    - sec
    - create_nginx_certs

- name: Create git repos root @create_nginx_git_repo
  file:
    path: "{{ var_dp_git_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
  tags:
    - dp
    - sec
    - create_nginx_git_repo

- name: Configure safe.directory for www-data @config_nginx_git_repo
  git_config:
    name: safe.directory
    value: "{{ var_dp_git_root }}/*"
    scope: system
  tags:
    - dp
    - sec
    - config_nginx_git_repo
    
- name: Deploy nginx site config @deploy_nginx_site
  template:
    src: git-http.conf.j2
    dest: /etc/nginx/sites-available/git-http
  notify: Nginx reloaded
  tags:
    - dp
    - sec
    - deploy_nginx_site

- name: Enable git-http site @enable_nginx_site
  file:
    src: /etc/nginx/sites-available/git-http
    dest: /etc/nginx/sites-enabled/git-http
    state: link
  notify: Nginx reloaded
  tags:
    - dp
    - sec
    - enable_nginx_site

- name: Start fcgiwrap service @start_fcgiwrap
  command: spawn-fcgi -s {{ var_dp_fcgi_socket }} -M 766 /usr/sbin/fcgiwrap
  args:
    creates: "{{ var_dp_fcgi_socket }}"
  register: fcgi_result
  changed_when: fcgi_result.rc == 0 and fcgi_result.stdout is search("spawned")
  tags:
    - dp
    - sec
    - start_fcgiwrap
